Name: Pranav Shelke
Roll No : 123
Batch: B-T3
Assignmnet Title: Array


Array Attributes

In [34]:
import numpy as np

In [35]:
a1 = np.array([ 1, 34, 55])
arr

[1, 34, 55]

In [36]:
a2= np.array([[1,2,3,4,5],[5,6,7,8,9]])
arr1


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [37]:
a1.ndim

1

In [38]:
a2.ndim

2

In [39]:
a2.shape

(2, 5)

In [40]:
arr1 = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18]
])
print(arr1.size)
print(arr1.ndim)
print(arr1.shape)

18
2
(3, 6)


In [41]:
arr2 = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])
arr2.dtype

dtype('int64')

In [44]:
arr2 = np.array([
    [1, 2.4, 3, 4, 5.5, 6],
    [7, 8.1, 9, 10.6, 11, 12]
])
arr2.dtype

dtype('float64')

In [45]:
arr2 = np.array([
    [1, 2.4, 3, 4, 5.5, 6],
    ['z', 8, 9, 10, 11, 'a']
])
arr2.dtype

dtype('<U32')

In [47]:
arr1 = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])
arr1.itemsize

8

Array Indexing

In [49]:
import numpy as np
ar = np.array([
    [1, 2, 3, 4, 5, 6],
    [13, 14, 15, 16, 17, 18]
])
ar


array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18]])

In [61]:
print(ar[1][1])
print(ar[1:2])

14
[[13 14 15 16 17 18]]


In [60]:
print(ar[0][3])

4


In [ ]:
a =np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
a = np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [72]:
a= np.arange(9)
b= a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Arithmetic Operations

In [78]:
a = np.array([1, 2, 3 ,8])
b = np.array([4, 2, 6, 3])
print(a + b)


[ 5  4  9 11]


In [79]:
print(a / b)

[0.25       1.         0.5        2.66666667]


In [80]:
print(a - b)

[-3  0 -3  5]


In [81]:
print(a * b)

[ 4  4 18 24]


In [82]:
arr = np.array([10, 30, 20 ,80])
np.argmax(arr)

np.int64(3)

In [83]:
arr = np.array([10, 30, 20, 4 ,5 ,1])
np.argmin(arr)

np.int64(5)

In [85]:
arr = np.array([10, 30, 20, 30.1])
np.argmax(arr)

np.int64(3)

In [86]:
a = np.array([1, 3, 6, 10, 15, 18])
np.diff(a)

array([2, 3, 4, 5, 3])

In [88]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])